apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: node-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-db
  serviceName: db
  template:
    metadata:
      labels:
        app: node-db
      name: node-db
    spec:
      containers:
        - name: node-container-db
          image: postgres:12-alpine
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: db-configmap